salary_thresholds:
  upper: 50_000
  lower: 6_136

contribution_percentages:
  current:
    employee:
      below_threshold: 5
      above_threshold: 5
    employer: 
      below_threshold: 0
      above_threshold: 3
    tax_relief: 20
    combined_minimum: 8

frequency_conversions:
  salary_frequencies:
    year: 1
    month: 12
    fourweeks: 13
    week: 52
  tax_relief_limit_by_frequency:
    1:  8000
    12: 666.67
    13: 615.38
    52: 153.85
  tax_relief_on_salary_by_frequency:
    year: 12500
    month: 1042
    fourweeks: 960
    week: 240
  opt_in_thresholds_by_frequency:
    lower:
      year: 6240
      month: 520
      fourweeks: 480
      week: 120
    upper:
      year: 10000
      month: 833
      fourweeks: 768
      week: 192

session_expiry_limit: 30
