salary_thresholds:
  upper: 45_000
  lower: 5_876
full:
  employee:
    below_threshold: 3
    above_threshold: 1
  employer:
    below_threshold: 0
    above_threshold: 1
minimum:
  employee:
    below_threshold: 1
    above_threshold: 1
  employer:
    below_threshold: 1
    above_threshold: 1
