salary_thresholds:
  upper: 46_350
  lower: 6_032
full:
  employee:
    below_threshold: 3
    above_threshold: 1
  employer:
    below_threshold: 0
    above_threshold: 1
minimum:
  employee:
    below_threshold: 3
    above_threshold: 3
  employer:
    below_threshold: 2
    above_threshold: 2
