april_2017_march_2018:
  tax_relief_percent: 20
april_2018_march_2019:
  employee_percent: 3
  employer_percent: 2
  tax_relief_percent: 20
after_april_2019:
  employee_percent: 5
  employer_percent: 3
  tax_relief_percent: 20
