salary_frequencies:
  year: 1
  month: 12
  fourweeks: 13
  week: 52
tax_relief_limit_by_frequency:
  1:  8000
  12: 666.67
  13: 615.38
  52: 153.85
tax_relief_on_salary_by_frequency:
  year: 11850
  month: 987.50
  fourweeks: 911.54
  week: 227.88
manual_opt_in_by_frequency:
  lower:
    year: 6032
    month: 503
    fourweeks: 464
    week: 116
  upper:
    year: 10000
    month: 833
    fourweeks: 768
    week: 192
