#!/bin/bash -l

source ~/.bashrc
rvm use default

export RAILS_ENV=production
exit_code=0

function run {
    declare -a build_command=("$@")

    echo ''
    echo "=== Running \`${build_command[*]}\`"
    if ! ${build_command[*]}; then
        echo "=== This build failed."
        exit_code=1
    fi
}

# (re)install node packages to local dir before tests run

run npm install
run bundle install
run bundle exec bowndler install --allow-root
run gem install geminabox
run gem build wpcc.gemspec
run gem inabox *.gem -g http://gems.dev.mas.local

exit "$exit_code"
