#!/bin/bash

docker build -t wpcc .
docker run \
    --interactive \
    --tty \
    --rm \
    -v "$PWD:/var/tmp/repo" \
    -w /var/tmp/repo \
    wpcc \
        ./script/test

if [ $? = 0 ]; then
    echo "All tests passed."
else
    echo "Test(s) failed."
fi
