#!/bin/bash -l

source ~/.bashrc
rvm use default

export RAILS_ENV=test
exit_code=0

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}

# (re)install node packages to local dir before tests run

run npm install
run bundle install
run bundle exec bowndler install --allow-root
run bundle exec brakeman -z
run bundle exec rubocop .
run bundle exec rspec
run bundle exec cucumber
run ./node_modules/karma/bin/karma start spec/javascripts/karma.conf.js --single-run

exit "$exit_code"
