#!/bin/bash

export RAILS_ENV=test
exit_code=0

function run_tests {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit_code=1
    fi
}


# (re)install node packages to local dir before tests run
npm install
bundle exec bowndler install


run_tests bundle exec brakeman -z
run_tests bundle exec rubocop .
run_tests bundle exec rspec
run_tests bundle exec cucumber
run_tests ./node_modules/karma/bin/karma start spec/javascripts/karma.conf.js --single-run

exit "$exit_code"
