Feature: Near limit messaging for users earning close to lower salary threshold
  In order to understand that I am close to the pension threshold
  As a worker earning the lower salary threshold ± 10
  I want to be notified that my calculation might not be correct

  Background:
  Given I am on the Your Details step
  And I fill in my details

  @no-javascript
  Scenario Outline: Viewing my details on step 2 and my salary is close to the lower Manual Opt In limits
    And my salary is "<salary>" "<salary_frequency>" with "Full" contribution
    And I submit my details
    Then I should see the warning "<message>"

    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6134   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 6142   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 502    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 513    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 464    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 474    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 116    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 126    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |

    @welsh
    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6134   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 6140   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 502    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 513    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 474    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 476    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 116    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 126    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |

  @no-javascript
  Scenario Outline: Viewing my details on step 2 and my salary is not close to the lower Manual Opt In limits
    And my salary is "<salary>" "<salary_frequency>" with "Full" contribution
    And I submit my details
    Then I should NOT see the warning "<message>"

    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6021   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 6043   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 492    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 523    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 453    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 485    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 105    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 137    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |

    @welsh
    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6021   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 6043   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 492    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 524    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 453    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 485    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 105    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 129    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |

  @javascript
  Scenario Outline: Entering my salary when it is close to the lower Manual Opt In limits
    When my salary is "<salary>" "<salary_frequency>" with "Full" contribution
    Then I should see the warning "<message>"

    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6126   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 6142   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 503    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 513    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 464    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 474    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 116    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 126    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |

    @welsh
    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6132   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 6142   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 503    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 513    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 464    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 474    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 116    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 126    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |

  @javascript
  Scenario Outline: Entering my salary when it is not close to the lower Manual Opt In limits
    And my salary is "<salary>" "<salary_frequency>" with "Full" contribution
    And I submit my details
    Then I should NOT see the warning "<message>"

    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6021   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 6043   | per year         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 492    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 524    | per month        | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 453    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 485    | per 4 weeks      | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 105    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 129    | per week         | Please note: Your earnings are very close to the threshold at which your employer does not have to contribute to your pension if you choose to enrol. You should check to confirm whether or not your employer will contribute as this threshold varies depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |

    @welsh
    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 6021   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 6043   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 492    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 524    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 453    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 485    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 105    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 129    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy lle nad oes raid i’ch cyflogwr gyfrannu at eich pensiwn os dewiswch gofrestru. Dylech wirio i gadarnhau a fydd eich cyflogwr yn cyfrannu neu beidio oherwydd mae’r trothwy hwn yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
