Feature: Near auto-enrollment messaging for users earning close to £10,000 per year
  In order to understand that I am close to the automatic enrollment threshold of £10,000
  As a worker earning £10,000 ± 10
  I want to be notified that my calculation might not be correct

  Background:
  Given I am on the Your Details step
  And I fill in my details

  @no-javascript
  Scenario Outline: Viewing my details on step 2 and my salary is close to the lower Manual Opt In limits
    And my salary is "<salary>" "<salary_frequency>" with "Full" contribution
    And I submit my details
    Then I should see the warning "<message>"

    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 9990   | per year         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 10010  | per year         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 823    | per month        | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 843    | per month        | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 758    | per 4 weeks      | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 778    | per 4 weeks      | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 182    | per week         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 202    | per week         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |

    @welsh
    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 9990   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 10010  | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 823    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 843    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 758    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 778    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 182    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 202    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |

  @no-javascript
  Scenario Outline: Viewing my details on step 2 and my salary is close to the lower Manual Opt In limits
    And my salary is "<salary>" "<salary_frequency>" with "Full" contribution
    And I submit my details
    Then I should NOT see the warning "<message>"

    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 9989   | per year         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 10011  | per year         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 322    | per month        | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 844    | per month        | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 757    | per 4 weeks      | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 779    | per 4 weeks      | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 181    | per week         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |
      | 203    | per week         | Please Note: Your earnings are very close to the automatic enrolment salary threshold. You should check with your employer to confirm whether or not you are eligible to be automatically enrolled as the thresholds vary depending on whether you are paid monthly, weekly or 4-weekly. Read more about the salary thresholds for workplace pensions. |

    @welsh
    Examples:
      | salary | salary_frequency | message                                                                                                                                                                           |
      | 9989   | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 10011  | y flwyddyn       | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 322    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 844    | y mis            | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 757    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 779    | fesul 4 wythnos  | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 181    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
      | 203    | y wythnos        | Sylwer: Mae eich enillion yn agos iawn at y trothwy cyflog cofrestru awtomatig. Dylech wirio gyda’ch cyflogwr i gadarnhau a ydych yn gymwys neu beidio i gael eich cofrestru’n awtomatig gan fod y trothwyon yn amrywio yn ddibynnol ar a ydych yn cael eich talu’n fisol, wythnosol neu bob 4 wythnos. Darllenwch fwy am y trothwyon cyflog ar gyfer pensiynau gweithle. |
