name: Test

on: push

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: 1.17.2
          bundler-cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '14.x'

      - name: Install bower
        run: npm install -g bower

      - name: Install bowndler packages
        run: bundle exec bowndler install && bundle exec bowndler update

      - name: Run npm install
        run: npm install

      - name: Run cucumber tests
        run: bundle exec cucumber

      - name: Run tests
        run: bundle exec rspec
